version: "3.7"

services:
  grin:
    build: .
    ports:
      - "3414:3414"
      - "13414:13414"
      - "13415:13415"
    volumes:
      - "grin-data:/home/grinuser/.grin"
    environment:
      - USER=grinuser

volumes:
  grin-data:
